name: 'Issue to Page'
author: 'phish108'
description: 'Converts an issue to a markdown page'
branding:
  icon: printer
  color: green
inputs:
  auto-convert:
    description: 'automatically publish the page for selected users'
    required: false
    default: '_OWNER'
  close-issue:
    description: 'close the issue after conversion'
    required: false
    default: 'true'
  github-token:
    description: "the token to access github"
    default: ${{ github.token }}
    required: false
  issue-template:
    description: 'template used for the issue'
    required: false
  label:
    description: 'issue label to handle'
    required: false
  publish-label: 
    description: 'secondary label to use for publishing'
    required: false
    default: 'publish'
  target-folder:
    description: 'target folder in the repository'
    required: false
    default: "/"
  template:
    description: 'template to use to render the issue'
    required: false
  formhints:
    description: 'YAML file that hints how to parse the issue body'
    required: false
    default: formhints.yml

runs:
  using: node20
  main: 'action/index.js'
